"""initial schema

Revision ID: ef1631122581
Revises: 
Create Date: 2026-05-28 08:17:22.261719

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ef1631122581'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('approval_ref', sa.String(), nullable=False),
    sa.Column('evidence_only', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('export_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_trace_id'), 'audit_logs', ['trace_id'], unique=False)
    op.create_table('benefit_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pond_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('source_mode', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edge_nonces',
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('seen_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_table('export_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('pond_id', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('redacted', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('redaction_policy', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('ponds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_id', sa.String(), nullable=False),
    sa.Column('source_mode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('batch_key', sa.String(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_key')
    )
    op.create_table('threshold_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('warning_below', sa.Float(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('source_mode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('credential_hash', sa.String(), nullable=False),
    sa.Column('credential_salt', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('pond_scope', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pond_id', sa.String(), nullable=False),
    sa.Column('source_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('recommendation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_pond_id'), 'alerts', ['pond_id'], unique=False)
    op.create_table('devices',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('pond_id', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('source_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_devices_pond_id'), 'devices', ['pond_id'], unique=False)
    op.create_table('media_samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pond_id', sa.String(), nullable=False),
    sa.Column('sample_type', sa.String(), nullable=False),
    sa.Column('object_ref', sa.String(), nullable=False),
    sa.Column('source_mode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_samples_pond_id'), 'media_samples', ['pond_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pond_id', sa.String(), nullable=False),
    sa.Column('source_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommendation_type', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=False),
    sa.Column('proposed_minutes', sa.Integer(), nullable=False),
    sa.Column('weather_source', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_pond_id'), 'recommendations', ['pond_id'], unique=False)
    op.create_table('water_readings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('pond_id', sa.String(), nullable=False),
    sa.Column('captured_at', sa.String(), nullable=False),
    sa.Column('dissolved_oxygen_mg_l', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('source_mode', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.String(), nullable=False),
    sa.Column('source_qualifiers', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_readings_captured_at'), 'water_readings', ['captured_at'], unique=False)
    op.create_index(op.f('ix_water_readings_event_id'), 'water_readings', ['event_id'], unique=True)
    op.create_index(op.f('ix_water_readings_pond_id'), 'water_readings', ['pond_id'], unique=False)
    op.create_table('control_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('execution_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dissolved_oxygen_mg_l', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('density_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('source_mode', sa.String(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('estimated_density_fish_m2', sa.Float(), nullable=False),
    sa.Column('error_margin_fish_m2', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('recommendation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['media_samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_deliveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('provider_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_deliveries_alert_id'), 'notification_deliveries', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_deliveries_alert_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_table('density_analyses')
    op.drop_table('control_executions')
    op.drop_index(op.f('ix_water_readings_pond_id'), table_name='water_readings')
    op.drop_index(op.f('ix_water_readings_event_id'), table_name='water_readings')
    op.drop_index(op.f('ix_water_readings_captured_at'), table_name='water_readings')
    op.drop_table('water_readings')
    op.drop_index(op.f('ix_recommendations_pond_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_media_samples_pond_id'), table_name='media_samples')
    op.drop_table('media_samples')
    op.drop_index(op.f('ix_devices_pond_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_alerts_pond_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('threshold_rules')
    op.drop_table('sync_batches')
    op.drop_table('ponds')
    op.drop_table('export_records')
    op.drop_table('edge_nonces')
    op.drop_table('benefit_metrics')
    op.drop_index(op.f('ix_audit_logs_trace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('archive_records')
    # ### end Alembic commands ###
